version: '3.1'

services:

    db:
        image: postgres:latest
        container_name: guacamole_postgres
        restart: always
        networks:
          mynet:
            ipv4_address: 192.168.1.35
        environment:
            POSTGRES_USER: haili
            POSTGRES_PASSWORD: veganpi
            POSTGRES_DB: guacamole_db
    networks:
        mynet:
            external: true


    adminer:
        image: adminer:latest
        container_name: guacamole_adminer
        restart: always
        networks:
          mynet:
            ipv4_address: 192.168.1.35
        ports:
            - 8080:8080
    networks:
        mynet:
            external: true
