---
version: "2.1"

services:

  openvpn-as:
    image: ghcr.io/linuxserver/openvpn-as
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /home/kali/docker_stuff/pivpn:/config
    hostname: openvpn # set an easy hostname to remember
    networks:
      mynet: # same as network specified below
        ipv4_address: 192.168.1.52 # the IP of the container
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped

networks:
  mynet:   # externally created network
    external: true
