version: "3.9"

services:
  pihole:
    container_name: pihole53
    image: pihole/pihole:latest
    hostname: pihole53
    cap_add:
      - NET_ADMIN
    networks:
      asgard: # same as network specified below
        ipv4_address: 192.168.10.53 # the IP of the pihole container
    dns:
      - 127.0.0.1 # use local DNS, since the pihole 
      - 1.1.1.1 # optional fallback DNS
    ports: # expose all pihole ports.
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './backups/:/backups/'
    environment:
      ServerIP: 192.168.10.53 # must match ipv4_address above
      VIRTUAL_HOST: pihole.exampledomain
      WEBPASSWORD: "veganpi"
      TZ: 'Asia/Jerusalem'
    restart: unless-stopped

  homer:
      container_name: homer
      image: b4bz/homer:latest
      hostname: homer
      networks:
        asgard: # same as network specified below
          ipv4_address: 192.168.10.50 # the IP of the container
      ports: # expose all pihole ports.
        - 8080:8080
      volumes: # mount our data volumes.
        - /home/kali/docker_stuff/homer:/www/assets
      user: 0:0
      environment:
        - INIT_ASSETS=1 # default
      restart: unless-stopped


networks:
  asgard:   # externally created network
    external: true
