version: "3"

services:
  # Ouroboros: Automatically update your running Docker containers to the latest available image
  # https://github.com/pyouroboros/ouroboros
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    networks:
      - macvlan
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=${TZ} 
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Pihole: Network-wide Ad Blocking
  # https://hub.docker.com/r/pihole/pihole
  pihole:
    container_name: pihole53
    image: pihole/pihole:latest
    hostname: pihole53
    cap_add:
      - NET_ADMIN
    networks:
      - macvlan
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ports:
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    volumes:
      - '${DOCKER_PATH}/pihole/etc-pihole/:/etc/pihole/'
      - '${DOCKER_PATH}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - '${DOCKER_PATH}/pihole/backups/:/backups/'
    environment:
      WEBPASSWORD: ${PASS}
      TZ: ${TZ}
    restart: unless-stopped

  # Homer: A fancy homepage for self-hosted services
  # https://hub.docker.com/r/b4bz/homer
  homer:
    container_name: homer
    image: b4bz/homer:latest
    hostname: homer
    networks:
      - macvlan
    ports:
      - 8080:8080
    volumes:
      - ${DOCKER_PATH}/homer:/www/assets
    user: 0:0
    environment:
      - INIT_ASSETS=1
    restart: unless-stopped

  # DuckDNS Dynamic DNS server
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - macvlan
    environment:
      - PUID=${UID} #optional
      - PGID=${GID} #optional
      - TZ=${TZ}
      - SUBDOMAINS=${DOMAIN}
      - TOKEN=${TOKEN}
      - LOG_FILE=true #optional
    volumes:
      - ${DOCKER_PATH}/duckdns_config:/config
    restart: unless-stopped

  # All-in-one: WireGuard + Web UI
  # https://github.com/WeeJeWel/wg-easy
  wg-easy:
    environment:
      - WG_HOST=${DOMAIN}
      - PASSWORD=${PASS}
      - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 8.8.8.8
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
    image: weejewel/wg-easy
    container_name: wg-easy
    depends_on:
      - duckdns
    networks:
      - macvlan
    volumes:
      - ${DOCKER_PATH}/wg-easy:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  # Home Assistant for home automations
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    networks:
      - macvlan
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_PATH}/home-assistant:/config
    ports:
      - 8123:8123 #optional
    restart: unless-stopped

  # Nextcloud - self hosted cloud service
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_mariadb
    restart: always
    networks:
      - macvlan
    volumes:
      - ${DOCKER_PATH}/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud_db
    networks:
      - macvlan
    ports:
      - 8888:80
    links:
      - nextcloud_db
    volumes:
      - ${DOCKER_PATH}/nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${USER}
      - MYSQL_HOST=db

  # Vaultwarden - Selfhosted password manager
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    networks:
      - macvlan
    expose:
      - "80"
      - "3012"
    volumes:
      - ${DOCKER_PATH}/vaultwarden/data:/data
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      TZ: ${TZ}

  # Portainer - Docker deployement GUI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    networks:
      - macvlan
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_PATH}/portainer:/data

  # Guacamole - Remote Session manager
  # Elastic Stack and Elatic Security

networks:
  macvlan:
    name: ${NET}
    driver: macvlan
    driver_opts:
      parent: ${PARENT_INTERFACE}
    ipam:
      config:
        - subnet: ${SUBNET}
          gateway: ${GATEWAY}
          ip_range: ${IP_RANGE}
          aux_addresses:
            host: ${AUX}