version: "2"

services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    hostname: homer
    networks:
      asgard: # same as network specified below
        ipv4_address: 192.168.10.50 # the IP of the pihole container
    ports: # expose all pihole ports.
      - 8080:8080
    volumes: # mount our data volumes.
      - /home/kali/docker_stuff/homer:/www/assets
    user: 0:0
    environment: # set variables for pihole configuration.
      - INIT_ASSETS=1 # default
    restart: unless-stopped

networks:
  asgard:   # externally created network
    external: true
