version: '3'

services:
  ubuntu:
    image: ubuntu:latest
    container_name: ubuntu
    restart: unless-stopped
    networks:
      mynet: # network name
        ipv4_address: 192.168.1.51 # the IP of the container
    command: "tail -f /dev/null"

networks:
  mynet:   # network again
    external: true
